package br.edu.ifpi.associapp.enuns;

public enum GrauDeInstucaoEnum {

	ANALFABETO,
	ALFABETIZADO,
	FUNDAMENTALINCOMPLETO,
	FUNDAMENTALCOMPLETO,
	MEDIOINCOMPLETO,
	MEDIOCOMPLETO,
	UNIVERSITARIOINCOMPLETO,
	UNIVERSITARIOCOMPLETO;
	
}
